/**
 * Constants, or all actions that can happen within this app
 */

export const TOGGLE_FILTER = 'REDUX-FILTER/TOGGLE_FILTER';
export const KEYWORD_SEARCH = 'REDUX-FILTER/KEYWORD_SEARCH';
export const TOGGLE_FILTER_ONLY = 'REDUX-FILTER/TOGGLE_FILTER_ONLY';
export const CLEAR_FILTERS = 'REDUX-FILTER/CLEAR_FILTERS';
export const APPLY_SORT = 'REDUX-FILTER/APPLY_SORT';
export const CLEAR_ALL_FILTERS = 'REDUX-FILTER/CLEAR_ALL_FILTERS';
export const GO_TO_PAGE = 'REDUX-FILTER/GO_TO_PAGE';

export const UPDATE_SUBJECTS = 'REDUX-FILTER/UPDATE_SUBJECTS';
export const INIT = 'REDUX-FILTER/INIT';
